-- Intellectro social vertical slice.
-- Governance note: RLS is enabled before live persistence is considered ready.
create extension if not exists pgcrypto;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, handle text not null unique check (char_length(handle) between 2 and 40), display_name text not null check (char_length(display_name) between 1 and 80), bio text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.spaces (id uuid primary key default gen_random_uuid(), slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'), name text not null check (char_length(name) between 2 and 100), description text not null default '', created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now());
create table public.space_memberships (space_id uuid not null references public.spaces(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member' check (role in ('member','moderator','admin')), created_at timestamptz not null default now(), primary key (space_id,user_id));
create table public.posts (id uuid primary key default gen_random_uuid(), space_id uuid not null references public.spaces(id) on delete cascade, author_id uuid not null references auth.users(id) on delete cascade, body text not null check (char_length(body) between 1 and 20000), kind text not null default 'human' check (kind in ('human','source_linked','ai_assisted')), ai_assisted boolean not null default false, ai_assistance_type text, agent_id text, human_approved boolean, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.comments (id uuid primary key default gen_random_uuid(), post_id uuid not null references public.posts(id) on delete cascade, author_id uuid not null references auth.users(id) on delete cascade, body text not null check (char_length(body) between 1 and 10000), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reactions (post_id uuid not null references public.posts(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, reaction text not null check (reaction in ('like','useful','interesting')), created_at timestamptz not null default now(), primary key (post_id,user_id,reaction));
create table public.claim_responses (id uuid primary key default gen_random_uuid(), post_id uuid not null references public.posts(id) on delete cascade, author_id uuid not null references auth.users(id) on delete cascade, response_type text not null check (response_type in ('support','challenge','qualify','add_evidence','ask_question')), body text not null check (char_length(body) between 1 and 10000), created_at timestamptz not null default now());
create table public.sources (id uuid primary key default gen_random_uuid(), created_by uuid not null references auth.users(id) on delete cascade, url text not null, title text, publisher text, published_at timestamptz, created_at timestamptz not null default now());
create table public.post_sources (post_id uuid not null references public.posts(id) on delete cascade, source_id uuid not null references public.sources(id) on delete cascade, added_by uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key (post_id,source_id));
create table public.provenance_records (id uuid primary key default gen_random_uuid(), post_id uuid references public.posts(id) on delete cascade, source_refs jsonb not null default '[]'::jsonb, transformations jsonb not null default '[]'::jsonb, generated_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.agent_actions (id uuid primary key default gen_random_uuid(), agent_id text not null, owner_id uuid not null references auth.users(id) on delete restrict, space_id uuid references public.spaces(id) on delete cascade, action text not null, capability text not null, policy_version text not null, approval_status text not null check (approval_status in ('not_required','pending','approved','rejected')), input_refs jsonb not null default '[]'::jsonb, output_refs jsonb not null default '[]'::jsonb, created_at timestamptz not null default now());
create table public.approval_records (id uuid primary key default gen_random_uuid(), action_id uuid not null references public.agent_actions(id) on delete cascade, approver_id uuid not null references auth.users(id) on delete restrict, decision text not null check (decision in ('approved','rejected')), note text not null default '', created_at timestamptz not null default now(), unique (action_id,approver_id));
create table public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references auth.users(id) on delete cascade, post_id uuid references public.posts(id) on delete cascade, comment_id uuid references public.comments(id) on delete cascade, reason text not null, status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')), created_at timestamptz not null default now(), check ((post_id is not null)::int + (comment_id is not null)::int = 1));
create table public.blocks (blocker_id uuid not null references auth.users(id) on delete cascade, blocked_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key (blocker_id,blocked_id), check (blocker_id <> blocked_id));
create table public.mutes (muter_id uuid not null references auth.users(id) on delete cascade, muted_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key (muter_id,muted_id), check (muter_id <> muted_id));

create index posts_space_created_idx on public.posts (space_id, created_at desc);
create index comments_post_created_idx on public.comments (post_id, created_at);
create index claim_responses_post_created_idx on public.claim_responses (post_id, created_at);
create index agent_actions_space_created_idx on public.agent_actions (space_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.spaces enable row level security;
alter table public.space_memberships enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.reactions enable row level security;
alter table public.claim_responses enable row level security;
alter table public.sources enable row level security;
alter table public.post_sources enable row level security;
alter table public.provenance_records enable row level security;
alter table public.agent_actions enable row level security;
alter table public.approval_records enable row level security;
alter table public.reports enable row level security;
alter table public.blocks enable row level security;
alter table public.mutes enable row level security;

create policy "profiles authenticated read" on public.profiles for select to authenticated using (true);
create policy "profiles own insert" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "profiles own update" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "spaces authenticated read" on public.spaces for select to authenticated using (true);
create policy "spaces creator insert" on public.spaces for insert to authenticated with check (auth.uid() = created_by);
create policy "spaces creator update" on public.spaces for update to authenticated using (auth.uid() = created_by) with check (auth.uid() = created_by);
create policy "memberships authenticated read" on public.space_memberships for select to authenticated using (true);
create policy "memberships self join" on public.space_memberships for insert to authenticated with check (auth.uid() = user_id and role = 'member');
create policy "memberships self leave" on public.space_memberships for delete to authenticated using (auth.uid() = user_id and role = 'member');
create policy "posts authenticated read" on public.posts for select to authenticated using (true);
create policy "posts own insert" on public.posts for insert to authenticated with check (auth.uid() = author_id);
create policy "posts own update" on public.posts for update to authenticated using (auth.uid() = author_id) with check (auth.uid() = author_id);
create policy "posts own delete" on public.posts for delete to authenticated using (auth.uid() = author_id);
create policy "comments authenticated read" on public.comments for select to authenticated using (true);
create policy "comments own insert" on public.comments for insert to authenticated with check (auth.uid() = author_id);
create policy "comments own update" on public.comments for update to authenticated using (auth.uid() = author_id) with check (auth.uid() = author_id);
create policy "comments own delete" on public.comments for delete to authenticated using (auth.uid() = author_id);
create policy "reactions authenticated read" on public.reactions for select to authenticated using (true);
create policy "reactions own insert" on public.reactions for insert to authenticated with check (auth.uid() = user_id);
create policy "reactions own delete" on public.reactions for delete to authenticated using (auth.uid() = user_id);
create policy "claim responses authenticated read" on public.claim_responses for select to authenticated using (true);
create policy "claim responses own insert" on public.claim_responses for insert to authenticated with check (auth.uid() = author_id);
create policy "claim responses own delete" on public.claim_responses for delete to authenticated using (auth.uid() = author_id);
create policy "sources authenticated read" on public.sources for select to authenticated using (true);
create policy "sources own insert" on public.sources for insert to authenticated with check (auth.uid() = created_by);
create policy "sources own update" on public.sources for update to authenticated using (auth.uid() = created_by) with check (auth.uid() = created_by);
create policy "sources own delete" on public.sources for delete to authenticated using (auth.uid() = created_by);
create policy "post sources authenticated read" on public.post_sources for select to authenticated using (true);
create policy "post sources own insert" on public.post_sources for insert to authenticated with check (auth.uid() = added_by);
create policy "post sources own delete" on public.post_sources for delete to authenticated using (auth.uid() = added_by);
create policy "provenance authenticated read" on public.provenance_records for select to authenticated using (true);
create policy "agent actions owner read" on public.agent_actions for select to authenticated using (auth.uid() = owner_id);
create policy "approval action owner read" on public.approval_records for select to authenticated using (exists (select 1 from public.agent_actions aa where aa.id = action_id and aa.owner_id = auth.uid()));
create policy "approval human insert" on public.approval_records for insert to authenticated with check (auth.uid() = approver_id);
create policy "reports own read" on public.reports for select to authenticated using (auth.uid() = reporter_id);
create policy "reports own insert" on public.reports for insert to authenticated with check (auth.uid() = reporter_id);
create policy "blocks own read" on public.blocks for select to authenticated using (auth.uid() = blocker_id);
create policy "blocks own insert" on public.blocks for insert to authenticated with check (auth.uid() = blocker_id);
create policy "blocks own delete" on public.blocks for delete to authenticated using (auth.uid() = blocker_id);
create policy "mutes own read" on public.mutes for select to authenticated using (auth.uid() = muter_id);
create policy "mutes own insert" on public.mutes for insert to authenticated with check (auth.uid() = muter_id);
create policy "mutes own delete" on public.mutes for delete to authenticated using (auth.uid() = muter_id);
